# Generated by Django 5.2.6 on 2025-09-29 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='type',
        ),
    ]
